<html>
<head>
    <title>Api Doc</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
        .method {
            border: 1px solid;
            padding: 4px;
            margin-right: 10px;
        }

        div.lightBlue {
            background-color: #7ACAFF !important;
        }
        span.lightBlue {
            background-color: #94ccf1;
        }

        span.lightBlue:hover {
            background-color: #6dabd4;
        }

        a:hover, a:focus {
            text-decoration: none;
        }


    </style>
</head>
<body>

<div class="page-header">
    <h1>This is API autogenerated <small>Lortom CMS</small></h1>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    @php
    $i=0;
    @endphp
    @foreach($routes as $route)
    <div class="lightBlue panel panel-info">
        <div class="panel-heading " role="tab" id="heading-{{$i}}">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-{{$i}}" aria-expanded="true" aria-controls="collapse-{{$i}}">
                    <span class="method lightBlue"> {{$route['method']}} </span>   {{$route['uri']}}
                </a>
            </h4>
        </div>
        <div id="collapse-{{$i}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-{{$i}}">
            <div class="panel-body">
                @if(isset($route['object']))
                    {{$route['object']['description']}}
                @else
                    <div class="alert alert-warning" role="alert">There is no description avaiable</div>
                @endif
            </div>
        </div>
    </div>
        <?php
            $i++;
        ?>
    @endforeach
</div>

<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>